trigger:
- master

pool:
  vmImage: 'windows-2019'

stages:
- stage: Build
  jobs:
  - job: BuildModules
    steps:
    - task: PowerShell@2
      displayName: PSBuild Modules
      enabled: true
      inputs:
        filePath: "buildPSSolution.ps1"
        arguments: ""
