trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildModules
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: PowerShell@2
      displayName: PSBuild Modules
      enabled: true
      inputs:
        filePath: "Build-PSSolution.ps1"
        pwsh: true