trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildModules
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: PowerShell@2
      displayName: Prepare Pipeline Agent
      enabled: true
      inputs:
        filePath: "Prepare-PipelineAgent.ps1"
        pwsh: true
    - task: PowerShell@2
      displayName: PSBuild Modules
      enabled: true
      inputs:
        filePath: "Build-PSSolution.ps1"
        pwsh: true
    - task: PublishPipelineArtifact@0
      displayName: Pulbish Artifact
      enabled: true
      inputs:
        artifactName: psmodules
        targetpath: '.\'